"""Prometheus metrics exporter for DPI-LS cost metrics.

Exports real-time cost metrics from the database to Prometheus format
for consumption by Prometheus and Grafana dashboards.
"""
from __future__ import annotations

import logging
from typing import Dict, Any

from prometheus_client import Gauge, Info, REGISTRY
from sqlalchemy.orm import Session

from store import repo

logger = logging.getLogger(__name__)

def get_or_create_gauge(name: str, documentation: str, labelnames: list[str]) -> Gauge:
    """Helper to return an existing Gauge from the registry or create a new one."""
    # Find existing collector in the registry
    collector = REGISTRY._names_to_collectors.get(name)
    if collector and isinstance(collector, Gauge):
        return collector
    return Gauge(name, documentation, labelnames)

# Create Prometheus metrics for all cost dimensions
cost_metrics = {
    'dpi_ls_input_tokens': get_or_create_gauge(
        'dpi_ls_input_tokens',
        'Number of input tokens consumed by agent',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_output_tokens': get_or_create_gauge(
        'dpi_ls_output_tokens',
        'Number of output tokens generated by agent',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_prompt_cost': get_or_create_gauge(
        'dpi_ls_prompt_cost',
        'Cost of input tokens in USD',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_completion_cost': get_or_create_gauge(
        'dpi_ls_completion_cost',
        'Cost of output tokens in USD',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_model_cost': get_or_create_gauge(
        'dpi_ls_model_cost',
        'Total model cost (prompt + completion) in USD',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_ai_cost_per_output': get_or_create_gauge(
        'dpi_ls_ai_cost_per_output',
        'AI cost per completed output in USD',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_human_cost_per_output': get_or_create_gauge(
        'dpi_ls_human_cost_per_output',
        'Human cost per output in USD (from settings)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_utilization': get_or_create_gauge(
        'dpi_ls_utilization',
        'Agent utilization ratio (0-1)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_efficiency_ratio': get_or_create_gauge(
        'dpi_ls_efficiency_ratio',
        'Efficiency ratio (human cost / AI cost)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_cost_score': get_or_create_gauge(
        'dpi_ls_cost_score',
        'Normalized cost score (0-5)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_validation_score': get_or_create_gauge(
        'dpi_ls_validation_score',
        'Normalized validation score (0-1)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_quality_score': get_or_create_gauge(
        'dpi_ls_quality_score',
        'Normalized quality score (0-1)',
        ['agent_id', 'agent_name']
    ),
    'dpi_ls_tco': get_or_create_gauge(
        'dpi_ls_tco',
        'Total cost of ownership (human + AI) in USD',
        ['agent_id', 'agent_name']
    ),
    'final_score': get_or_create_gauge(
        'final_score',
        'Overall DPI-LS final score',
        ['agent_id', 'agent_name']
    ),
}

# System info metric
# Find or create Info metric
info_collector = REGISTRY._names_to_collectors.get('dpi_ls_info')
if info_collector and isinstance(info_collector, Info):
    dpi_ls_info = info_collector
else:
    dpi_ls_info = Info(
        'dpi_ls_info',
        'DPI-LS system information'
    )


def export_cost_metrics(session: Session) -> None:
    """Export current cost metrics from database to Prometheus.

    This function is called periodically to update Prometheus metrics
    with the latest cost data from the DPI-LS database.
    """
    try:
        # Get latest scores for all agents
        scores = repo.latest_scores_for_all(session)
        settings = repo.get_settings(session)

        logger.info(f"Found {len(list(scores))} agents for metrics export")

        # Set system info
        dpi_ls_info.info({
            'version': '1.0.0',
            'environment': 'production'
        })

        # Convert to list since we may iterate multiple times
        scores_list = list(repo.latest_scores_for_all(session))
        logger.info(f"Processing {len(scores_list)} agent scores")

        for agent, score in scores_list:
            if not agent or agent.id != "chandra-finops":
                continue

            logger.info(f"Processing agent {agent.id} with score {bool(score)}")

            if score is None:
                logger.warning(f"No score for agent {agent.id}")
                continue

            if not score.sub_metrics:
                logger.warning(f"No sub_metrics for agent {agent.id}")
                continue

            agent_id = agent.id
            agent_name = agent.name or agent.id
            labels = [agent_id, agent_name]

            # Extract cost sub-metrics
            cost_sub = score.sub_metrics.get('C', {})
            if not cost_sub:
                logger.warning(f"No cost sub-metrics for agent {agent_id}")
                continue

            logger.info(f"Exporting {len(cost_sub)} cost metrics for agent {agent_id}")

            # Update all cost metrics
            if 'input_tokens' in cost_sub:
                cost_metrics['dpi_ls_input_tokens'].labels(*labels).set(
                    float(cost_sub['input_tokens'])
                )

            if 'output_tokens' in cost_sub:
                cost_metrics['dpi_ls_output_tokens'].labels(*labels).set(
                    float(cost_sub['output_tokens'])
                )

            if 'Prompt Cost (USD)' in cost_sub:
                cost_metrics['dpi_ls_prompt_cost'].labels(*labels).set(
                    float(cost_sub['Prompt Cost (USD)'])
                )

            if 'Completion Cost (USD)' in cost_sub:
                cost_metrics['dpi_ls_completion_cost'].labels(*labels).set(
                    float(cost_sub['Completion Cost (USD)'])
                )

            if 'Model Cost (USD)' in cost_sub:
                cost_metrics['dpi_ls_model_cost'].labels(*labels).set(
                    float(cost_sub['Model Cost (USD)'])
                )

            if 'AI Cost Per Output' in cost_sub:
                cost_metrics['dpi_ls_ai_cost_per_output'].labels(*labels).set(
                    float(cost_sub['AI Cost Per Output'])
                )

            if 'Human Cost / Output' in cost_sub:
                cost_metrics['dpi_ls_human_cost_per_output'].labels(*labels).set(
                    float(cost_sub['Human Cost / Output'])
                )

            if 'utilization' in cost_sub:
                cost_metrics['dpi_ls_utilization'].labels(*labels).set(
                    float(cost_sub['utilization'])
                )

            if 'Efficiency Ratio' in cost_sub:
                cost_metrics['dpi_ls_efficiency_ratio'].labels(*labels).set(
                    float(cost_sub['Efficiency Ratio'])
                )

            # Cost score is the C metric value
            if score.metrics and 'C' in score.metrics and score.metrics['C'] is not None:
                cost_score = float(score.metrics['C'])
                cost_metrics['dpi_ls_cost_score'].labels(*labels).set(cost_score)

            if score.metrics and 'V' in score.metrics and score.metrics['V'] is not None:
                cost_metrics['dpi_ls_validation_score'].labels(*labels).set(float(score.metrics['V']))
                
            if score.metrics and 'Q' in score.metrics and score.metrics['Q'] is not None:
                cost_metrics['dpi_ls_quality_score'].labels(*labels).set(float(score.metrics['Q']))

            if 'Total Cost (USD)' in cost_sub:
                cost_metrics['dpi_ls_tco'].labels(*labels).set(
                    float(cost_sub['Total Cost (USD)'])
                )

            # Update final_score
            cost_metrics['final_score'].labels(*labels).set(
                float(score.score or 0.0)
            )

        logger.info(f"Exported metrics for {len([s for _, s in scores if s])} agents")

    except Exception as e:
        logger.error(f"Failed to export cost metrics: {e}")


def get_metrics_summary(session: Session) -> Dict[str, Any]:
    """Get a summary of current metrics for debugging."""
    try:
        scores = repo.latest_scores_for_all(session)
        summary = {}

        for agent, score in scores:
            if score is None:
                continue

            agent_id = agent.id
            cost_sub = score.sub_metrics.get('C', {}) if score.sub_metrics else {}

            summary[agent_id] = {
                'input_tokens': cost_sub.get('input_tokens'),
                'output_tokens': cost_sub.get('output_tokens'),
                'prompt_cost': cost_sub.get('Prompt Cost (USD)'),
                'completion_cost': cost_sub.get('Completion Cost (USD)'),
                'model_cost': cost_sub.get('Model Cost (USD)'),
                'ai_cost_per_output': cost_sub.get('AI Cost Per Output'),
                'human_cost_per_output': cost_sub.get('Human Cost / Output'),
                'utilization': cost_sub.get('utilization'),
                'efficiency_ratio': cost_sub.get('Efficiency Ratio'),
                'cost_score': score.metrics.get('C') if score.metrics and 'C' in score.metrics and score.metrics.get('C') is not None else None,
                'tco': cost_sub.get('Total Cost (USD)'),
            }

        return summary

    except Exception as e:
        logger.error(f"Failed to get metrics summary: {e}")
        return {}