"""Cost Service — dynamic cost registry, calculation, and audit logging.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Optional
from sqlalchemy.orm import Session

from store import repo
from store.models import AgentCostValueRow, CostMetricDefinitionRow

logger = logging.getLogger("dpi_ls.cost_service")

# Standard Cost Metric definitions per requirements
STANDARD_METRICS = [
    # AI Cost
    ("llm_token_cost", "ai", "LLM Token Cost", "Raw token cost for large language models", "Langfuse/OpenAI", "USD"),
    ("prompt_cost", "ai", "Prompt Cost", "Cost generated by prompt tokens", "Langfuse", "USD"),
    ("completion_cost", "ai", "Completion Cost", "Cost generated by completion tokens", "Langfuse", "USD"),
    ("model_cost", "ai", "Model Cost", "General model API cost", "AWS Bedrock/OpenAI", "USD"),
    ("api_cost", "ai", "API Cost", "External SaaS/AI API charges", "Stripe/Vendor", "USD"),
    ("bedrock_usage_cost", "ai", "Bedrock Usage Cost", "AWS Bedrock specific model charges", "AWS Bedrock Metrics", "USD"),
    ("aws_cost", "ai", "AWS Cost", "General AWS resource charges", "AWS Billing", "USD"),
    ("infrastructure_cost", "ai", "Infrastructure Cost", "Compute, memory, cluster runtime costs", "AWS Cost Explorer", "USD"),

    # Human Cost
    ("salary_cost", "human", "Salary Cost", "Salary cost of human worker baseline", "SAP HR/Workday", "USD"),
    ("time_spent", "human", "Time Spent", "Hours spent by humans on manual task execution", "Jira/Timesheets", "Hours"),
    ("operational_effort", "human", "Operational Effort", "Operational overhead/maintenance effort", "Jira", "USD"),
    ("opportunity_cost", "human", "Opportunity Cost", "Lost value from manual processing delays", "Business Finance", "USD"),
    ("manual_processing_effort", "human", "Manual Processing Effort", "Cost of manual QA/SOP processing", "QMS Registry", "USD"),

    # System Cost
    ("storage_cost", "system", "Storage Cost", "Disk, S3, vector DB storage costs", "AWS Cost Explorer/Pinecone", "USD"),
    ("compute_cost", "system", "Compute Cost", "EC2, ECS, Lambda runtimes", "CloudWatch", "USD"),
    ("database_cost", "system", "Database Cost", "Aurora, RDS, PostgreSQL query costs", "AWS Cost Explorer", "USD"),
    ("logging_cost", "system", "Logging Cost", "Log ingestion and retention costs", "CloudWatch/Datadog", "USD"),
    ("monitoring_cost", "system", "Monitoring Cost", "APM, dashboard, trace billing", "Datadog/NewRelic", "USD"),

    # Business Cost
    ("cost_per_output", "business", "Cost per Output", "Calculated cost per completed transaction", "DPI-LS Engine", "USD"),
    ("cost_per_transaction", "business", "Cost per Transaction", "Direct operational transaction cost", "APM logs", "USD"),
    ("cost_per_request", "business", "Cost per Request", "Cost of single LLM query/interaction", "LLM Gateway", "USD"),
    ("total_cost_of_ownership", "business", "Total Cost of Ownership (TCO)", "All-inclusive digital worker lifecycle cost", "Finance", "USD"),
    ("utilization_factor", "business", "Utilization Factor", "Ratio of active processing time to idle time", "Prometheus/CloudWatch", "Ratio"),
]


def register_standard_metrics(s: Session) -> None:
    """Pre-populate the database with the standard 23 cost metrics."""
    for metric_id, category, display_name, description, source, unit in STANDARD_METRICS:
        repo.save_cost_metric_definition(
            s=s,
            metric_id=metric_id,
            category=category,
            display_name=display_name,
            description=description,
            source_system=source,
            unit=unit,
        )
    logger.info("Registered standard cost metric definitions.")


class CostService:
    """Orchestrates dynamic calculations, audit logging, and scoring injection."""

    @staticmethod
    def calculate_costs(
        s: Session,
        agent_id: str,
        period_start: datetime,
        period_end: datetime,
        completed_outputs: int = 1,
        fallback_human_cost: float = 1.0,
        fallback_utilization: float = 1.0,
    ) -> dict[str, Any]:
        """Aggregate dynamic cost metrics in the given period and compute TCO/ratios."""
        # 1. Fetch all cost values for the agent in this period
        values = repo.list_agent_cost_values(s, agent_id, period_start, period_end)
        definitions = {d.id: d for d in repo.list_cost_metric_definitions(s)}

        total_ai = 0.0
        total_human = 0.0
        total_system = 0.0
        total_business = 0.0
        utilization = fallback_utilization
        input_tokens = 0
        output_tokens = 0
        number_of_llm_calls = 0

        # Detailed breakdown for audit trail and logs
        audit_details = []

        # 2. Sum values by category
        for v in values:
            defn = definitions.get(v.metric_id)
            cat = defn.category if defn else "ai"
            
            # Map specific metrics to tokens/calls for the Cost model
            if v.metric_id == "input_tokens":
                input_tokens += int(v.value)
            elif v.metric_id == "output_tokens":
                output_tokens += int(v.value)
            elif v.metric_id == "number_of_llm_calls":
                number_of_llm_calls += int(v.value)
            elif v.metric_id == "utilization_factor":
                utilization = max(0.0, min(1.0, v.value))

            if cat == "ai":
                total_ai += v.value
            elif cat == "human":
                total_human += v.value
            elif cat == "system":
                total_system += v.value
            elif cat == "business":
                total_business += v.value

            audit_details.append({
                "metric_id": v.metric_id,
                "category": cat,
                "value": v.value,
                "period": f"{v.period_start.isoformat()} to {v.period_end.isoformat()}"
            })

        # Calculate TCO
        tco = total_ai + total_system + total_human + total_business

        # AI cost per output: dynamic if we have dynamic AI spend
        # Model cost is the sum of raw AI costs and system infrastructure costs
        dynamic_model_cost = total_ai + total_system
        outputs = completed_outputs if completed_outputs > 0 else 1
        ai_cost_per_output = dynamic_model_cost / outputs

        # Human cost per output
        if total_human > 0:
            human_cost_per_output = total_human / outputs
        else:
            human_cost_per_output = fallback_human_cost

        # 3. Write structured audit log
        audit_msg = (
            f"[AUDIT LOG] Cost calculation for agent '{agent_id}' from {period_start} to {period_end}:\n"
            f"  - Completed Outputs: {outputs}\n"
            f"  - Dynamic Model Cost (AI + System): ${dynamic_model_cost:.6f}\n"
            f"  - AI Cost Per Output: ${ai_cost_per_output:.6f}\n"
            f"  - Human Cost Per Output: ${human_cost_per_output:.6f}\n"
            f"  - TCO: ${tco:.6f}\n"
            f"  - Utilization: {utilization:.2f}\n"
            f"  - Values aggregated: {len(values)}\n"
            f"  - Breakdown: {audit_details}"
        )
        logger.info(audit_msg)

        return {
            "agent_id": agent_id,
            "period_start": period_start,
            "period_end": period_end,
            "model_cost": dynamic_model_cost,
            "Human_cost": total_human if total_human > 0 else fallback_human_cost * outputs,
            "human_cost_per_output": human_cost_per_output,
            "ai_cost_per_output": ai_cost_per_output,
            "utilization": utilization,
            "tco": tco,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "number_of_llm_calls": number_of_llm_calls,
            "audit_trail": audit_details,
        }
